In [1]:
import numpy as np
import torch

In [8]:
x = torch.rand(3,2)
x

tensor([[0.0211, 0.1823],
        [0.4028, 0.7685],
        [0.7174, 0.7884]])

In [9]:
y = torch.ones(x.size())
y

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [15]:
z = x + y
z

tensor([[1.0211, 1.1823],
        [1.4028, 1.7685],
        [1.7174, 1.7884]])

In [16]:
z[:,1:]

tensor([[1.1823],
        [1.7685],
        [1.7884]])

In [17]:
z.add(1)

tensor([[2.0211, 2.1823],
        [2.4028, 2.7685],
        [2.7174, 2.7884]])

In [18]:
z

tensor([[1.0211, 1.1823],
        [1.4028, 1.7685],
        [1.7174, 1.7884]])

In [19]:
z.add_(1)

tensor([[2.0211, 2.1823],
        [2.4028, 2.7685],
        [2.7174, 2.7884]])

In [20]:
z

tensor([[2.0211, 2.1823],
        [2.4028, 2.7685],
        [2.7174, 2.7884]])

In [21]:
z.size()

torch.Size([3, 2])

In [22]:
z.resize_(2,3)

tensor([[2.0211, 2.1823, 2.4028],
        [2.7685, 2.7174, 2.7884]])

In [23]:
z

tensor([[2.0211, 2.1823, 2.4028],
        [2.7685, 2.7174, 2.7884]])

In [25]:
a = np.random.rand(4,3)
a

array([[0.67252743, 0.28783404, 0.58553706],
       [0.37724164, 0.67201407, 0.30406332],
       [0.60424528, 0.96554302, 0.82276494],
       [0.70623415, 0.35897843, 0.87041978]])

In [26]:
b = torch.from_numpy(a)
b

tensor([[0.6725, 0.2878, 0.5855],
        [0.3772, 0.6720, 0.3041],
        [0.6042, 0.9655, 0.8228],
        [0.7062, 0.3590, 0.8704]], dtype=torch.float64)

In [28]:
b.numpy()

array([[0.67252743, 0.28783404, 0.58553706],
       [0.37724164, 0.67201407, 0.30406332],
       [0.60424528, 0.96554302, 0.82276494],
       [0.70623415, 0.35897843, 0.87041978]])

In [31]:
b.mul_(2)

tensor([[1.3451, 0.5757, 1.1711],
        [0.7545, 1.3440, 0.6081],
        [1.2085, 1.9311, 1.6455],
        [1.4125, 0.7180, 1.7408]], dtype=torch.float64)

In [32]:
a

array([[1.34505485, 0.57566808, 1.17107411],
       [0.75448328, 1.34402813, 0.60812663],
       [1.20849056, 1.93108604, 1.64552989],
       [1.4124683 , 0.71795685, 1.74083955]])